# Generated by Django 2.2 on 2019-12-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=55)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.Dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=250)),
                ('frecuencia', models.PositiveIntegerField()),
                ('descripcion_fecha', models.CharField(max_length=150)),
                ('cant_actividades_cumplidas', models.PositiveIntegerField()),
                ('cant_actividades_no_realizadas', models.PositiveIntegerField()),
                ('medios_verificacion', models.CharField(max_length=200)),
                ('dependencias', models.ManyToManyField(to='poa.Dependencia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.EstadoActividad')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cna.Objetivo')),
            ],
        ),
    ]
