# Generated by Django 2.2 on 2019-12-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cna.Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=500)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cna.Caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='MetaLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cna.Caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='MetaCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cna.Caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='FactorCna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cna.Programa')),
            ],
        ),
    ]
