# Generated by Django 2.2 on 2019-12-29 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='factor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cna.FactorCna'),
            preserve_default=False,
        ),
    ]
